{% set name = "w3g" %}
{% set version = "1.0.4" %}
{% set sha256 = "00b37b3c790f3f5a4bc7190eb8afb3912ebe052d8afe1dd9bb0562c174854a40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - w3g

about:
  home: http://github.com/scopatz/w3g
  license: CC0
  license_family: OTHER
  license_file: license
  summary: Access Warcraft 3 replay files from Python 2 or 3

extra:
  recipe-maintainers:
    - scopatz
