{% set name = "w3g" %}
{% set version = "1.0.2" %}
{% set sha256 = "38b2420f1f931a02ec9b9d992d9c890e62526070d3b92f3bf3fdfddb25ceb57f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - w3g

about:
  home: http://github.com/scopatz/w3g
  license: CC0
  license_family: OTHER
  license_file: license
  summary: 'Access Warcraft 3 replay files from Python 2 or 3'

extra:
  recipe-maintainers:
    - scopatz
