travis:
  secure:
    BINSTAR_TOKEN: JfhjJe6BYotKo9p4SifVVeNJCbZ+ehFTX6nDr3VwXBAofxVvPCE78VdtBvPG57DVQzwZ9l1brMAdMN2Ma2rUWCz5oBg0w9eEEi61CR8LfRrH1wEFMJVhyoG4f/c/JWlkgsSqmp7FvaSc1s0Ro1rbpF6shdNxiv1R13tWcLTQzxsqHsgDt/0zx5xHTUu6pmI/5GS6pNiIkyM4B121yxU00fw9GdpNw42+BFIGJ84IX02g4B4Zd1i+R+j92BnOuWwGyW4kGPUUv4773SXpDqy0WdRL4Y6tE1FQWHLs2f51epjCtj67SDNYeWo0Uj5i2r60RNMnAlRYB43/ukopLwNn/0TkJag2i2orU43gXWCquL+9gQBLKK/AI3ZroRYZuekLY4eqqVVJ5GFGBgsbiUgXA6Dw3eiVqDycSZZJTK9zwUeGWkHwe61haEPuxA/7u7xfPMeXExpokOlXVQ64pmqabYR1Uo2LM/7byr1ZgeSvhAp/sh33hbz6YIjg3WgC53cKRgsQxW1li6WmSMmoof4//gVJu32/zk6P0mgr1Uk1bHxcfVMvTMEBqQAI/jZ+vAaUWAkcwrbNwTXyYQAisW3XBZaaLuDltg2AGI4gSGHFIOhHlTACUoe1ktF4OqNmWHMjXLNogsuS9az/DZ+eKluIXHtLBwd2tqIPpWILaRg4kq4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
