travis:
  secure:
    BINSTAR_TOKEN: bq8vIlQJarurHwYI1eLAT978wldmePZBAoe1IFx+hAtClKZy5tXtbf+yWMrObTpAp27Df3RYQgzc09UtuGivq1rcxJ67tgKbHHuyHAXhjPu3Gvmxpp2Co6me3pq4ffsVjF9X5+Sz/4BLGWX4zJRpPagscd9GwW0mnc/vbzB+4HG1pBmOkPxe54eqZ0tyi6ljs72SiTXrmcV9XTfcEAfaQTTCgYpxLscZ5JRNPImrV7WK/KSj43Rrpm0mPwyyjUBaDtMlZLdOS/Cr1MBswIMdsws+1/RSGOTB6/s++cvmAKe+uk6M7rR7Qh2ZEiSs3wKGrwYWZpk4W37pcGPjQIzXWLYkcq0p+325bWAD2ihuN1Q6k9FiXBDAKBZae1G5TE3wRIaxHoGb+lXLtuVsvaR1njhWMy0JJzyCiSRZXT43Vj8XW0n+xfE9L7+rVACzMosFRWx/ku/NHwrjN7yArMqytunzE5XuTHwC8IDIiG59ZK0T+H+yrWJqR1ClOd39rSRgwHvQqlLzMa/UjxJk93vaJ33gW5FQJvL4S1jeNlUSRBQigBjlGQLSBPhRM3j8lkNehvAV3uFwFCJGVZwRZcL8z4VIl4fDMOmhyLJsx9Vz9L7/uhGSO9t+C8yvSo4kpSeJ+KFAtsS2OArMpseSj4jvpTWhf7J1mIkTtCpA6FV/rHs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
